### ISSUE TITLE
为什么loss为负值？（Why is loss Negative value?）

### ISSUE THREAD

**Issue by lvvsh** [Chnja/SRCNet#2]
I followed reedme and used LEVIR-CD as the data set. When running train.py, I found that loss was negative value. Would you like to know why?

**Comment by Chnja** [comment]
Beacause we used a principled approach to multitask deep learning proposed by Kendall et al.
A. Kendall, Y. Gal, and R. Cipolla, “Multi-task learning using uncertainty to weigh losses for scene geometry and semantics,” in Proc. IEEE Conf. Comput. Vis. Pattern Recognit., 2018, pp. 7482–7491.
